export type SalesInquiryFollowup = {
  APIUniqueId: number;
  AlternateUnitQuantity: number;
  AmendNo: number;
  ChangableItem: boolean;
  ConversionFactor: number;
  CostGroupMasterId: number;
  DesignNo: string;
  DetailDescription: string;
  DocumentDate: string;
  DocumentNo: number;
  EvaluationStatus: number;
  GodownMasterAPIDetailId: number;
  GodownMasterId: number;
  ItemMasterId: number;
  LoginDetailsTransactionId: number;
  MachineName: string;
  PackSize: number;
  PartyName: string;
  Purity: number;
  Quantity: number;
  ReferenceDate: string;
  ReferenceNo: string;
  Remarks: string;
  RequiredSampleApprovalDispatch: boolean;
  RequiredSampleApprovalQuot: boolean;
  RequiredSampleWithDispatch: boolean;
  SalesInquiryDetailsId: number;
  SalesInquiryId: number;
  SalesQuotationDetailsId: number;
  SampleInwardDetailsId: number;
  SampleQuantity: number;
  SerialNo: number;
  TransactionMode: string;
  Unit: string;
  UnitQuantity: number;
  ImageName: string;
};

export type SalesQuotationFollowup = {
  AdditionalDiscountRate: number;
  AdditionalDiscountType: string;
  AdditionalFreeQuantity: number;
  AlternateUnitQuantity: number;
  AmendNo: number;
  ApprovedSampleDetailsId: number;
  ClaimQuantity: number;
  ConversionFactor: number;
  CostGroupMasterId: number;
  DeliveryWithinDays: number;
  DesignNo: string;
  DetailDescription: string;
  DiscountAmount: number;
  DiscountRate: number;
  DocumentDate: string;
  DocumentNo: number;
  FreeQuantity: number;
  GodownMasterId: number;
  IsPackSizeManualChange: boolean;
  ItemAmount: number;
  ItemMasterId: number;
  LandedAmount: number;
  LoginDetailsTransactionId: number;
  MRP: number;
  MRPProductRateGenerationDetailsId: number;
  MachineName: string;
  PackSize: number;
  ParentSalesQuotationDetailsId: number;
  PartyName: string;
  ProductCostingId: number;
  ProductRateGenerationDetailsId: number;
  Purity: number;
  Quantity: number;
  Rate: number;
  RateperQuantity: number;
  ReferenceDate: string;
  ReferenceNo: string;
  ReferenceRate: number;
  Remarks: string;
  SalesInquiryDetailsId: number;
  SalesOrderDetailsId: number;
  SalesQuotationDetailsId: number;
  SalesQuotationId: number;
  SampleFeedbackFromPartyDetailsId: number;
  SampleId: number;
  SampleNo: string;
  SchemeDetailsId: number;
  SerialNo: number;
  TaxAmount1: number;
  TaxAmount2: number;
  TaxAmount3: number;
  TaxAmount4: number;
  TaxAmount5: number;
  TaxAmount6: number;
  TaxAmount7: number;
  TaxAmount8: number;
  TaxAmount9: number;
  TaxAmount10: number;
  TaxAmount11: number;
  TaxAmount12: number;
  TaxPercentage1: number;
  TaxPercentage2: number;
  TaxPercentage3: number;
  TaxPercentage4: number;
  TaxPercentage5: number;
  TaxPercentage6: number;
  TaxPercentage7: number;
  TaxPercentage8: number;
  TaxPercentage9: number;
  TaxPercentage10: number;
  TaxPercentage11: number;
  TaxPercentage12: number;
  TransactionMode: string;
  Unit: string;
  UnitQuantity: number;
  ImageName: string;
};

export type InquiryFollowupInsert = {
  partyName: string;
  itemName: string;
  docNo: number;
  docDate: Date;
  quantity: number;
};

export type QuotationFollowupInsert = {
  partyName: string;
  itemName: string;
  docNo: number;
  docDate: Date;
  quantity: number;
};

export type SalesFollowupInsert = {
  DocumentDate: Date;
  SalesInquiryId: number;
  SalesInquiryDetailsId: number;
  SalesQuotationId: number;
  SalesQuotationDetailsId: number;
  FollowupDateTime: Date;
  FollowupEndDateTime: Date;
  FollowupDetails: string;
  FollowupStatus: string;
  ModeOfContact: string;
  documentSent: {
    offer: boolean;
    layout: boolean;
    pi: boolean;
  };
  VisitTo: string;
  VisitorPerson: string;
  NextVisitDateTime: Date;
  NextVisitPerson: string;
  NextVisitorPerson: string;
  AttentionDetails: string;
  OrderGoesParty: string;
  CloseReason: string;
  DetailDescription: string;
  Rating: string;
};

export type QuotationReminderData = {
  UserIdentification: string;
  UserCode: string;
  ReferenceTransaction_2361FollowupId: number;
  NextVisitDateTime: Date;
  FollowupStatus: string;
  FollowupDateTime: Date;
  FollowupDetails: string;
  CloseReason: string;
  ModeofContact: string;
  DetailDescription: string;
  VisitTo: string;
  LeadId: number;
  CompanyName: string;
}; 